config/routes.rb
Rails.application.routes.draw do
  devise_for :authors
  get 'home/index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "home#index"
  scope module: 'authors' do
    resources :posts do
      resources :elements
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/author.rb
class Author < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts
end

app/models/element.rb
class Element < ApplicationRecord
  belongs_to :post

  validates :element_type, inclusion: {in: ["paragraph", "image", "video-embed"]}

  has_rich_text :content
  has_one_attached :image

  def paragraph?
    element_type == "paragraph"
  end

  def image?
    element_type == "image"
  end

end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :author
  has_many :elements

  has_one_attached :header_image
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/authors/elements_controller.rb
module Authors
  class ElementsController < AuthorsController
    before_action :set_post
    before_action :set_element, only: [:update, :destroy]

    # POST /elements
    def create
      @element = @post.elements.build(element_params)

      notice = @element.save ? nil : @element.errors.full_messages.join(". ") << "."

      redirect_to edit_post_path(@post), notice: notice

    end

    # PATCH/PUT /elements/1
    def update
      @element.update(element_params)
      redirect_to edit_post_path(@element.post)
    end

    # DELETE /elements/1
    def destroy
      @element.destroy
      redirect_to edit_post_path(@element.post)
    end

    private
      # Use callbacks to share common setup or constraints between actions.

      def set_post
        @post = current_author.posts.find(params[:post_id])
      end

      def set_element
        @element = @post.elements.find(params[:id])
      end

      # Only allow a list of trusted parameters through.
      def element_params
        params.require(:element).permit(:element_type, :content, :image )
      end
  end
end

app/controllers/authors/posts_controller.rb
module Authors
  class PostsController < AuthorsController
    before_action :set_post, only: [:edit, :update, :destroy]

    # GET /posts
    def index
      @posts = current_author.posts
    end

    # GET /posts/new
    def new
      @post = current_author.posts.build
    end

    # GET /posts/1/edit
    def edit
      @element = @post.elements.build
    end

    # POST /posts
    def create
      @post = current_author.posts.build(post_params)

      if @post.save
        redirect_to edit_post_path(@post)
      else
        render :new
      end
    end

    # PATCH/PUT /posts/1
    def update
      if @post.update(post_params)
        redirect_to edit_post_path(@post)
      else
        render :edit
      end
    end

    # DELETE /posts/1
    def destroy
      @post.destroy
      redirect_to posts_url, notice: 'Post was successfully destroyed.'
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_post
        @post = current_author.posts.find(params[:id])
      end

      # Only allow a list of trusted parameters through.
      def post_params
        params.require(:post).permit(:title, :description, :header_image)
      end
  end
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  before_action :authenticate_author!

  layout 'authors'
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/elements_helper.rb
module ElementsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/authors/posts/_form.html.erb
<%= form_with(model: post) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>
      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-group">
    <%= form.label :title %>
    <%= form.text_field :title, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= form.label :description %>
    <%= form.text_area :description, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= form.label :header_image %>
    <%= form.file_field :header_image, class: "form-control" %>
    <div class="mt-1">
      <small>Current image:</small>
      <% if post.header_image.present? %>
        <%= image_tag(post.header_image, width: "100%") %>
      <% end %>
    </div>
  </div>
  <div class="actions">
    <%= form.submit class: "btn btn-primary btn-block" %>
  </div>
<% end %>

app/views/authors/posts/edit.html.erb
<div class="row">
  <div class="col-md-3">
    <%= link_to "Back", posts_path, class: "btn btn-secondary mb-3" %>
    <div class="card">
      <dif class="card-header">
        <h6 clas="card-title mb-0">Editing Post</h6>
      </dif>
      <div class="card-body">
        <%= render 'form', post: @post %>
      </div>
      <div class="card-footer">
        <% if @post.published? %>
          <a href="#"
            class="btn btn-secondary btn-block"
            data-reflex="click->PublisherReflex#unpublish"
            data-post-id="<%= @post.id %>">
            Unpublish
          </a>
        <% else %>
          <a href="#"
            class="btn btn-dark btn-block"
            data-reflex="click->PublisherReflex#publish"
            data-post-id="<%= @post.id %>">
            Publish
          </a>
        <% end %>
      </div>
    </div>
  </div>
  <div class="col-md-9">
    <div class="mb-3">
      <%= form_with(model: [@post, @element], html: {class: 'float-left mr-2'}) do |form| %>
        <%= form.hidden_field :element_type, value: "paragraph" %>
        <%= form.submit "Paragraph", class: "btn btn-dark" %>
      <% end %>
      <%= form_with(model: [@post, @element]) do |form| %>
        <%= form.hidden_field :element_type, value: "image" %>
        <%= form.submit "Image", class: "btn btn-dark" %>
      <% end %>
    </div>
    <div class="card">
      <div class="card-header text-right">
        <% if @post.published? %>
          <b>Published</b> <%= time_ago_in_words(@post.published_at) %> ago
        <% else %>
          Unpublished
        <% end %>
      </div>
      <div class="card-body pt-5">
        <% @post.elements.each do |element| %>
          <% if element.persisted? %>
            <% if element.paragraph? %>
              <div class="mb-4 p-3 paragraph">
                <div class="paragraph-content">
                  <% if element.content.present? %>
                    <%= element.content %>
                  <% else %>
                    Click to add content.
                  <% end %>
                </div>
                <div class="paragraph-form d-none">
                  <%= form_with(model: [@post, element]) do |form| %>
                    <%= form.rich_text_area :content %>
                    <div class="mt-3 d-flex justify-content-between">
                      <div>
                        <%= form.submit "Save", class: "btn btn-primary" %>
                        <a href="#" class='cancel btn btn-secondary'>Cancel</a>
                      </div>
                      <%= link_to 'Delete', post_element_path(@post, element), method: :delete, class: "btn btn-danger", data: {confirm: "Are you sure?"} %>
                    </div>
                  <% end %>
                </div>
              </div>
            <% elsif element.image? %>
              <div class="image mb-4 p-3">
                <% if element.image.present? %>
                  <div>
                    <%= image_tag(element.image) %>
                  </div>
                  <%= link_to 'Delete', post_element_path(@post, element), method: :delete, class: "btn btn-danger mt-2 float-right", data: {confirm: "Are you sure?"} %>
                <% else %>
                  <%= form_with(model: [@post, element]) do |form| %>
                    <%= form.file_field :image %>
                    <div class="mt-3">
                      <%= form.submit "Save" , class: "btn btn-primary" %>
                      <a href="#" class='cancel btn btn-secondary'>Cancel</a>
                    </div>
                  <% end %>
                <% end %>
              </div>
            <% end %>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/authors/posts/index.html.erb
<h4 class="d-flex justify-content-between mb-4">
  <span>Posts</span>
  <%= link_to 'New Post', new_post_path, class: 'btn btn-primary' %>
</h4>
<% @posts.each do |post| %>
  <%= link_to edit_post_path(post), class: 'text-decoration-none' do %>
    <div class="card mb-3 post-card">
      <div class="card-body">
        <div class="row">
          <div class="col-md-2">
            <% if post.header_image.present? %>
              <div class="header-img" style="background-image: url(<%= url_for(post.header_image) %>);"></div>
            <% end %>
          </div>
          <div class="col-md-10">
            <h5 class="card-title mb-1 text-dark"><%= post.title %></h5>
            <p class="text-secondary mb-0"><%= post.description %></p>
          </div>
        </div>
      </div>
    </div>
  <% end %>
<% end %>

app/views/authors/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>StevesBlog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/authors.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>StevesBlog</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css" integrity="sha384-zCbKRCUGaJDkqS1kPbPd7TveP5iyJE0EjAuZQTgFLD2ylzuqKfdKlfG/eSrtxUkn" crossorigin="anonymous">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body class="bg-light authors">
    <div class="container">
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
      <%= yield %>
    </div>
  </body>
</html>